name: integration-tests-app-ci

on:
  push:

permissions: {}

jobs:
  ios-integration-test:
    runs-on: macos-26
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Set Flutter version from FVM config file to environment variables
        id: fvm-config-action
        uses: kuhnroyal/flutter-fvm-config-action@fcdb62b682dade6f0d9e0c6eae6acc647ca8c31d

      - uses: subosito/flutter-action@fd55f4c5af5b953cc57a2be44cb082c8f6635e8e
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}

      - uses: futureware-tech/simulator-action@f6578e3385c735885cf408020b6fb455721dc57b
        id: simulator
        with:
          model: "iPhone 17"

      - name: Run integration tests
        env:
          SIMULATOR_UDID: ${{ steps.simulator.outputs.udid }}
        run: |
          flutter test integration_test/app_test.dart \
            -d $SIMULATOR_UDID